#ifndef __COMMON_DOT_H__
#define __COMMON_DOT_H__

#include <windows.h>

#define	u8	unsigned char
#define s8	signed char
#define u16	unsigned short
#define s16	signed short
#define u32	unsigned long
#define s32	signed long
#define u64	unsigned __int64
#define s64	signed __int64

//#define BYTE   unsigned char
#define SBYTE  signed char
//#define WORD   unsigned short
#define SWORD  signed short
//#define DWORD  unsigned long
#define SDWORD signed long
#define QWORD  unsigned __int64
#define SQWORD signed __int64

#endif