//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by rscript.rc
//
#define IDS_READY                       1
#define ID_TOGGLE_REGS                  2
#define IDS_COLOR_INVALID               2
#define ID_DUNNO                        3
#define IDS_CAPTURED                    3
#define ID_PLUGIN_VID_CONFIG            3
#define IDC_STEP                        3
#define ID_DUNNO2                       4
#define IDS_UK_ERROR                    4
#define ID_PLUGIN_VID_TEST              4
#define ID_OPTIONS_8MB                  4
#define IDS_DYN_MEM_FAIL                5
#define ID_PLUGIN_VID_ABOUT             5
#define IDS_BIG_DYN_SIZE                6
#define ID_PLUGIN_VID_APPLY             6
#define IDS_VIOLATION_ACCESS            7
#define ID_PLUGIN_AUD_CONFIG            7
#define IDS_NO_ADAPTOID                 8
#define ID_PLUGIN_AUD_TEST              8
#define IDS_ADAPTOIDS_FOUND             9
#define ID_PLUGIN_AUD_ABOUT             9
#define IDS_CPU_KILL                    10
#define ID_PLUGIN_AUD_APPLY             10
#define IDS_AUDIO_KILL                  11
#define ID_PLUGIN_CON_CONFIG            11
#define IDS_THREAD_DIE                  12
#define ID_PLUGIN_CON_TEST              12
#define IDS_EMU_STOPPED                 13
#define ID_PLUGIN_CON_ABOUT             13
#define IDS_CPU_UNPAUSED                14
#define ID_PLUGIN_CON_APPLY             14
#define IDS_EMU_STARTED                 15
#define ID_APPLY_ALL                    15
#define IDS_CPU_PAUSED                  16
#define IDS_EMU_PAUSED                  17
#define IDS_INVALID_ROM                 18
#define IDS_LOADED_NS                   19
#define IDS_LOADED_WS                   20
#define IDS_LOADED_DS                   21
#define IDS_OPEN_FAILED                 22
#define IDS_MEM_ALLOC                   23
#define IDS_MEM_ALLOC_ERROR             24
#define IDS_LOADING                     25
#define IDS_LOADED_100                  26
#define IDS_EMU_BEGIN                   27
#define IDS_NAN_FOUND                   28
#define IDS_TLBWR_CALLED                29
#define IDS_COUNT                       30
#define IDS_CRC_FAILED                  31
#define IDS_DELAY_DEAD                  32
#define IDS_COP2_CALLED                 33
#define IDS_NI_VERBOSE                  34
#define IDS_NI_CALLED                   35
#define IDS_BREAK_VERBOSE               36
#define IDS_BREAK_CALLED                37
#define IDS_MEM_LOAD                    38
#define IDS_MEM_LOAD_FAIL               39
#define IDS_DISCLAIMER                  40
#define IDS_SETTING_OLD                 41
#define IDS_CONSOLE_READY               42
#define IDS_DX_DEAD                     43
#define IDS_LOAD_CANCEL                 44
#define IDS_NEED_IMPLEMENT_ROMINFO      45
#define IDS_NEED_IMPLEMENT_SCREENSHOT   46
#define IDS_RECENT_FILE                 47
#define IDS_TITLE_SUFFIX                48
#define IDS_OPEN_TITLE                  49
#define IDS_PIF_UK                      50
#define IDS_RSP_UK                      51
#define IDS_DP_RUN                      52
#define IDI_APOLLO                      101
#define IDC_STATUS                      102
#define ID_MENU                         103
#define IDD_DLGABOUT                    104
#define IDD_DLGINFO                     105
#define IDD_DEBUGME                     106
#define IDD_PLUGINS                     108
#define IDD_REGS                        110
#define ID_HELP_BETAINFO                113
#define IDD_RECOMPDEBUG                 114
#define ID__RI_EC2                      1000
#define ID__RI_FNAME                    1001
#define ID__RI_INAME                    1002
#define ID__RI_BCODE                    1003
#define ID__RI_IC1                      1004
#define ID__RI_IC2                      1005
#define ID__RI_EC1                      1006
#define IDC_LASTCOMP                    1007
#define IDC_WINTITLE                    1008
#define IDC_DEBUGTREE                   1009
#define IDC_DEBUGLIST                   1010
#define IDC_DEBUGTAB                    1011
#define IDC_DEBUGADDRESS                1012
#define IDC_VIDEO_LIST                  1013
#define IDC_AUDIO_LIST                  1014
#define IDC_CONTROLLER_LIST             1015
#define IDC_R4KCODE                     1016
#define IDC_R4KSCROLL                   1017
#define IDC_X86CODE                     1018
#define IDC_X86SCROLL                   1019
#define IDC_REGR0                       1020
#define IDC_REGR1                       1021
#define IDC_REGR2                       1022
#define IDC_REGR3                       1023
#define IDC_REGR4                       1024
#define IDC_REGR5                       1025
#define IDC_REGR6                       1026
#define IDC_REGR7                       1027
#define IDC_REGR8                       1028
#define IDC_REGR9                       1029
#define IDC_REGR10                      1030
#define IDC_REGR11                      1031
#define IDC_REGR12                      1032
#define IDC_REGR13                      1033
#define IDC_REGR14                      1034
#define IDC_REGR15                      1035
#define IDC_REGR16                      1036
#define IDC_REGR17                      1037
#define IDC_REGR18                      1038
#define IDC_REGR19                      1039
#define IDC_REGR20                      1040
#define IDC_REGR21                      1041
#define IDC_REGR22                      1042
#define IDC_REGR23                      1043
#define IDC_REGR24                      1044
#define IDC_REGR25                      1045
#define IDC_REGR26                      1046
#define IDC_REGR27                      1047
#define IDC_REGR28                      1048
#define IDC_REGR29                      1049
#define IDC_REGR30                      1050
#define IDC_REGR31                      1051
#define IDC_REGEAX                      1052
#define IDC_REGEBX                      1053
#define IDC_REGECX                      1054
#define IDC_REGEDX                      1055
#define IDC_REGESI                      1056
#define IDC_REGEDI                      1057
#define IDC_REGESP                      1058
#define IDC_REGEBP                      1059
#define IDC_MAPEAX                      1060
#define IDC_MAPEBX                      1061
#define IDC_MAPECX                      1062
#define IDC_MAPEDX                      1063
#define IDC_MAPESI                      1064
#define IDC_MAPEDI                      1065
#define IDC_MAPESP                      1066
#define IDC_MAPEBP                      1067
#define IDC_GOTOLOC                     1068
#define IDC_GOTO                        1069
#define ID_FILE_EXIT                    40001
#define ID_FILE_CLOSEROM                40002
#define ID_OPTIONS_RUMBLE               40003
#define ID_FILE_ROMINFO                 40004
#define ID_FILE_SCREENSHOT              40005
#define ID_CPU_RESET                    40006
#define ID_CPU_PAUSE                    40007
#define ID_CPU_SAVESTATE                40008
#define ID_CPU_LOADSTATE                40009
#define ID_OPTIONS_VIDEO_WINDOWED_320X240 40010
#define ID_OPTIONS_VIDEO_WINDOWED_640X480 40011
#define ID_OPTIONS_VIDEO_WINDOWED_800X600 40012
#define ID_OPTIONS_VIDEO_FULLSCREEN_320X240 40013
#define ID_OPTIONS_VIDEO_FULLSCREEN_640X480 40014
#define ID_OPTIONS_VIDEO_FULLSCREEN_800X600 40015
#define ID_OPTIONS_VIDEO_FULLSCREEN_1024X768 40016
#define ID_OPTIONS_VIDEO_DEBUG_RDPDEBUGGER 40017
#define ID_OPTIONS_VIDEO_DEBUG_TEXTURECACHE 40018
#define ID_OPTIONS_VIDEO_DEBUG_WIREFRAME 40019
#define ID_OPTIONS_VIDEO_DRIVER         40020
#define ID_OPTIONS_AUDIO_ENABLED        40021
#define ID_OPTIONS_AUDIO_DEBUG_ABIDEBUGGER 40022
#define ID_OPTIONS_AUDIO_DEBUG_CACHESAMPLES 40023
#define ID_OPTIONS_CONTROLLER           40024
#define ID_HELP_ABOUT                   40025
#define ID_CONSOLE_TOGGLE               40026
#define ID_CONSOLE_SAVELOG              40027
#define ID_CONSOLE_CLEAR                40028
#define ID_CONSOLE_LOG                  40029
#define ID_CPU_DYNAREC_ROMTLB           40030
#define ID_CPU_DYNAREC_ROMMOD           40031
#define ID_CPU_DYNAREC_ENABLED          40032
#define ID_CPU_R4KDEBUGGER              40033
#define ID_DEBUG_OPENDEBUGGER           40033
#define ID_OPTIONS_VIDEO                40034
#define ID_OPTION_INPUT                 40035
#define ID_OPTIONS_INPUT                40035
#define ID_OPTIONS_SOUND                40036
#define ID_OPTIONS_320                  40037
#define ID_OPTIONS_640                  40038
#define ID_OPTIONS_800                  40039
#define ID_FILE_RECENT_FILE             40040
#define ID_CPU_COMPRESS                 40048
#define ID_OPTION_FULLSCREEN            40049
#define ID_OPTIONS_FULLSCREEN           40049
#define ID_OPTIONS_VSYNCHACK_1          40050
#define ID_OPTIONS_VSYNCHACK_2          40051
#define ID_OPTIONS_VSYNCHACK_3          40052
#define ID_OPTIONS_VSYNCHACK_4          40053
#define ID_OPTIONS_4KEEP                40054

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        115
#define _APS_NEXT_COMMAND_VALUE         40055
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
